[package]
name = "serde_arrow"
version = "0.5.0"
authors = ["Christopher Prohm <mail@cprohm.de>"]
edition = "2021"
description  = "convert sequences of structs / maps to arrow tables"
readme = "../Readme.md"
repository = "https://github.com/chmp/serde_arrow"
license = "MIT"

# [[bench]]
# name = "arrow"
# required-features = ["arrow"]
# harness = false

[dependencies]
# arrow = { version = "16.0", optional = true }
arrow2 = {version = "0.14", optional = true }

serde = "1.0"

# TODO: make optional, only required for str -> date conversions
chrono = "0.4"

[dev-dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
criterion = "0.3"
rand = "0.8"

[features]
arrow2-io_ipc = ["arrow2/io_ipc"]
