[package]
name = "example"
version = "0.1.0"
authors = ["Christopher Prohm <mail@cprohm.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "16.0"

chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }

serde_arrow = { path = "../serde_arrow", features = ["arrow", "arrow2", "arrow2-io_ipc"] }
serde_json = "1.0"
polars = { version = "0.21", features = ["dtype-i8"] }