{
  "name": "Release",
  "on": {
    "release": {
      "types": [
        "published"
      ]
    }
  },
  "env": {
    "CARGO_TERM_COLOR": "always"
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "env": {
        "CARGO_REGISTRY_TOKEN": "${{ secrets.CARGO_REGISTRY_TOKEN }}"
      },
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "name": "rustc",
          "run": "rustc --version"
        },
        {
          "name": "cargo",
          "run": "cargo --version"
        },
        {
          "name": "Check",
          "run": "cargo check"
        },
        {
          "name": "Check arrow2-0-16",
          "run": "cargo check --features arrow2-0-16"
        },
        {
          "name": "Check arrow2-0-17",
          "run": "cargo check --features arrow2-0-17"
        },
        {
          "name": "Check arrow-36",
          "run": "cargo check --features arrow-36"
        },
        {
          "name": "Check arrow-37",
          "run": "cargo check --features arrow-37"
        },
        {
          "name": "Check arrow-38",
          "run": "cargo check --features arrow-38"
        },
        {
          "name": "Check arrow-39",
          "run": "cargo check --features arrow-39"
        },
        {
          "name": "Build",
          "run": "cargo build --features arrow2-0-17,arrow-39"
        },
        {
          "name": "Test",
          "run": "cargo test --features arrow2-0-17,arrow-39"
        },
        {
          "name": "Publish to crates.io",
          "working-directory": "serde_arrow",
          "run": "cargo publish"
        }
      ]
    }
  }
}