name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rustc
      run: rustc --version
    - name: cargo version
      run: cargo --version
    - name: check
      run: cargo check --verbose
    - name: check arrow2-0-16
      run: cargo check --verbose --features arrow2-0-16
    - name: check arrow2-0-17
      run: cargo check --verbose --features arrow2-0-17
    - name: check arrow-36
      run: cargo check --verbose --features arrow-36
    - name: Build
      run: cargo build --verbose --features arrow2-0-17,arrow-36
    - name: Run tests
      run: cargo test --verbose --features arrow2-0-17,arrow-36
